### ISSUE TITLE
Configure docker insecure registries instead of pausing

### ISSUE THREAD

**Issue by jmontleon** [jmontleon/restricted-network-operator-mirror#2]
We can look for cases such as docker 1.13, docker-ce/moby-engine, and podman. Doing this manually is complicated by the fact that each uses a different file with a different format:

* /etc/sysconfig/docker for docker ~1.13
* /etc/docker/daemon.json for current moby-engine/docker-ce versions
* /etc/containers/registries.conf for podman (I guess some people link docker -> podman)

**Comment by rayfordj** [comment]
PR: https://github.com/jmontleon/restricted-network-operator-mirror/pull/9 addresses 'docker/daemon.json' case.  We'll still need to manually address the others for the time being.

**Comment by jmontleon** [comment]
I did away with the docker build/push and do an oc build instead to do away with the need to set up the insecure registry.
